#!/bin/bash

# install app
brew install macvim 
brew linkapps macvim
brew install ctags
curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

# link dotfiles
ln -s ~/.dotfiles/vim/.vimrc ~/.vimrc
ln -s ~/.dotfiles/.ctags ~/.ctags

# .zshrc
cat >> ~/.zshrc<<EOF
alias ll='ls -al'
alias vi='vim'
alias grep='grep --color=auto'
alias cls='clear'
EOF

# vim
# PlugInstall

